<?php
$z[0]=Array("field","",56,84);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",90,119);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\n          <dt> <img src=\"[field:picname/]\"> <a href=\"[field:arcurl/]\"> <b>[field:title/]</b>\n            <p>[field:description function=\"cn_substr(@me,100)\"/]... <span>[详细]</span></p>\n            </a> </dt>\n          ",172,463);
$z[2][4]['row']="1";
$z[2][4]['orderby']="click";
$z[2][4]['titlelen']="40";
$z[3]=Array("arclist"," <a href=\"[field:arcurl/]\"><em></em>[field:title/]<span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></a> ",479,648);
$z[3][4]['row']="5";
$z[3][4]['titlelen']="40";

?>