<li>
                        <div class="lbslt">
                            <a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]"  alt=""></a>
                        </div>
                        <div class="lbbiaoti">
                            <p><a href="[field:arcurl/]" class="fl" target="_blank">[field:title/]</a></p>
                        </div>
                        <div class="lbneirong ml10 mr10">
                            <p>[field:description function="cn_substr(@me,100)"/]...【<a href="[field:arcurl/]" target="_blank">详细</a>】</p>
                        </div>
                    </li>