<?php
$z[0]=Array("global","",156,189);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("zlqpic","",238,284);
$z[1][4]['function']="GetOneImgUrl(@me,1)";
$z[2]=Array("global","",348,381);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("zlhpic","",421,467);
$z[3][4]['function']="GetOneImgUrl(@me,1)";
$z[4]=Array("zlqh","",644,700);
$z[4][4]['function']="cn_substr(Html2text(\"@me\"),280)";
$z[5]=Array("zlh","",758,813);
$z[5][4]['function']="cn_substr(Html2text(\"@me\"),270)";
$z[6]=Array("arcurl","",822,837);

?>