<?php
$z[0]=Array("field","",81,103);
$z[0][4]['name']="typename";
$z[1]=Array("field","",112,133);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\n						<p class=\"item-pic\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"/></a></p>\n						",156,302);
$z[2][4]['limit']="0,1";
$z[2][4]['flag']="p";
$z[3]=Array("arclist","\n							<p><a href=\"[field:arcurl/]\">[field:title/]</a></p>\n							",340,463);
$z[3][4]['limit']="0,2";
$z[3][4]['titlelen']="100";

?>