<field:name itemname="姓名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:name>
<field:sex itemname="性别" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sex>
<field:age itemname="年龄" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:age>
<field:doctor itemname="主治医生" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:doctor>
<field:bqms itemname="病情描述" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bqms>
<field:zlqh itemname="治疗前" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="500" page="">
</field:zlqh>
<field:zlh itemname="治疗后" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="500" page="">
</field:zlh>
<field:story itemname="内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:story>

<field:zlqpic itemname="治疗前的图片" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zlqpic>
