<ul class="[field:global.autoindex runphp='yes']if(@me==0){@me='block';}else{@me='none';}[/field:global.autoindex] a[field:global name=autoindex runphp="yes"]@me=@me+1;[/field:global]-1">
                <li>
                    <div class="img">
                        <img src="/style/images/5_5.png" style="width:164px;">
                    </div>
                    <div class="inform">
                        <p>专家:</p>
                        <P>简介:</P>
                        <p>擅长:</p>
                    </div>
                    <a href="/swt/" class="phone">电话咨询</a>
                    <a href="/swt/" class="yel">预约挂号</a>
                </li>
				
                <li>
                    <div class="img">
                        <img src="{dede:global.cfg_cmsurl/}/style/images/5_5.png">
                    </div>
                    <div class="inform">
                        <p>专家:</p>
                        <P>简介:</P>
                        <p>擅长:</p>
                    </div>
                    <a href="#" class="phone">电话咨询</a>
                    <a href="#" class="yel">预约挂号</a>
                </li>
                <li>
                    <div class="img">
                        <img src="{dede:global.cfg_cmsurl/}/style/images/5_5.png">
                    </div>
                    <div class="inform">
                        <p>专家:</p>
                        <P>简介:</P>
                        <p>擅长:</p>
                    </div>
                    <a href="#" class="phone">电话咨询</a>
                    <a href="#" class="yel">预约挂号</a>
                </li>
                <li>
                    <div class="img">
                        <img src="{dede:global.cfg_cmsurl/}/style/images/5_5.png">
                    </div>
                    <div class="inform">
                        <p>专家:</p>
                        <P>简介:</P>
                        <p>擅长:</p>
                    </div>
                    <a href="#" class="phone">电话咨询</a>
                    <a href="#" class="yel">预约挂号</a>
                </li>
                <li>
                    <div class="img">
                        <img src="{dede:global.cfg_cmsurl/}/style/images/5_5.png">
                    </div>
                    <div class="inform">
                        <p>专家:</p>
                        <P>简介:</P>
                        <p>擅长:</p>
                    </div>
                    <a href="#" class="phone">电话咨询</a>
                    <a href="#" class="yel">预约挂号</a>
                </li>
                <li>
                    <div class="img">
                        <img src="{dede:global.cfg_cmsurl/}/style/images/5_5.png">
                    </div>
                    <div class="inform">
                        <p>专家:</p>
                        <P>简介:</P>
                        <p>擅长:</p>
                    </div>
                    <a href="#" class="phone">电话咨询</a>
                    <a href="#" class="yel">预约挂号</a>
                </li>
            </ul>