<?php
$z[0]=Array("global","if(@me==1){@me='block';}else{@me='none';}",11,107);
$z[0][4]['name']="itemindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","",109,133);
$z[1][4]['name']="itemindex";
$z[2]=Array("global","",763,788);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",1275,1300);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",1787,1812);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",2299,2324);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",2811,2836);
$z[6][4]['name']="cfg_cmsurl";

?>