<li>
                <h1><img src="[field:zjdt/]"></h1>
                <div class="team_ys right"> 
                  <div class="team_tit">
                     <b>[field:zjxm function='html2text(@me)'/]<em></em></b>
                     <p>[field:zjcz/]<br>[field:cysj/]</p>
                   </div>
				   <div class="clear"></div>
                   <div class="team_ms">
                     <p>[field:info/]</p>
                     <p><span>专业擅长：</span>[field:zysc/]</p>
                     <p><span>专家简介：</span>[field:zjjj/]<a href="[field:arcurl/]">【详细】</a></p>
                     
                     <div class="team_swt">
                     <a href="/swt/">我要和[field:zjxm/][field:zjcz/]直接对话</a></div>
                   </div>

                </div>
            </li>