<li style="height:30px">
                      <div class="picd"> 
                        <!--<a href="[field:arcurl/]" target="_blank"><img src="[field:zlqpic/]"></a>--> 
                      </div>
                      <div class="title"><!--<a href="[field:arcurl/]" target="_blank">--> 
                        恭喜:[field:name/]   电话:[field:tel_hiden/]   科室: [field:ks/]  预约成功 </div>
                    </li>