<!--channelid="18"-->
				 <h2>在这里，了解患者康复之路</h2>
                  <h3 style="margin-left: 0px">
				  <img src="[field:zlqpic function='GetOneImgUrl(@me,1)'/]"></h3>
                  <h3><img src="[field:zlhpic function='GetOneImgUrl(@me,1)'/]"></h3>
                  <h4><img src="/style/images/kf.jpg"></h4>
                  <ul>
                  <li style="margin-left: 0px"><p><span class="s1">治疗前</span>[field:zlqh function='cn_substr(Html2text("@me"),280)'/]</p></li>
                  <li><p><span>治疗后</span>[field:zlh function='cn_substr(Html2text("@me"),270)'/]<a href="[field:arcurl/]">【详细】</a></p></li>
                  </ul>