<?php
$z[0]=Array("field","",52,74);
$z[0][4]['name']="typename";
$z[1]=Array("field","",139,160);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\n            <li class=\"change_mouse\"> <img src=\"[field:litpic/]\">\n              <div class=\"child\">\n                <p><b><a href=\"[field:arcurl/]\">姓名</a>：</b> [field:name/]</p>\n                <p><b>性别：</b> [field:sex/]</p>\n                <p><b>年龄：</b> [field:age/]岁</p>\n                <p><b>主治医生：</b> [field:doctor/]</p>\n                <p><b>病情描述：</b> [field:bqms/]</p>\n              </div>\n            </li>\n            ",291,862);
$z[2][4]['row']="3";
$z[2][4]['addfields']="name,sex,age,doctor,bqms,story";
$z[2][4]['channelid']="18";
$z[2][4]['flag']="h";

?>