<li>
          <div class="lbslt"> <a href="[field:arcurl/]"><img src="[field:picname/]"  alt=""></a> </div>
          <div class="lbbiaoti">
            <p><a href="[field:arcurl/]" class="fl">[field:title/]</a></p>
          </div>
          <div class="lbneirong ml10 mr10">
            <p>[field:description function="cn_substr(@me,100)"/]...【<a href="[field:arcurl/]">详细</a>】</p>
          </div>
        </li>