<?php
$z[0]=Array("global","",168,201);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("zlqpic","",256,302);
$z[1][4]['function']="GetOneImgUrl(@me,1)";
$z[2]=Array("global","",373,406);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("zlhpic","",460,506);
$z[3][4]['function']="GetOneImgUrl(@me,1)";
$z[4]=Array("zlqh","",677,733);
$z[4][4]['function']="cn_substr(Html2text(\"@me\"),280)";
$z[5]=Array("zlh","",815,870);
$z[5][4]['function']="cn_substr(Html2text(\"@me\"),270)";
$z[6]=Array("arcurl","",879,894);

?>