<li>
		        	<a href="[field:arcurl/]">
		        		<img src="[field:litpic/]">
		        	</a><div class="pagedoc-li">
		        		<div class="pagedoc-li1">
		        			<h5>[field:title/]</h5>[field:zjcz function='cn_substr(@me,20)'/]
		        		</div>
		        		<div class="pagedoc-li2">
		        			<h6>诊疗擅长</h6>
		        			<p>[field:zysc function='cn_substr(@me,30)'/]/]</p>
		        		</div>
		        		<div class="pagedoc-li2">
		        			<h6>医生简介</h6>
		        			<p>[field:zjjj function='cn_substr(@me,60)'/]</p>
		        		</div>
		        		<div class="pagedoc-li2">
		        			<a class="pagedoc-li-a" href="[field:arcurl/]">专家详情</a>
		        			<a href="javascript:onKST();">预约挂号</a>
		        		</div>
		        	</div>
		        </li>