<field:zjxm itemname="专家姓名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zjxm>
<field:zjcz itemname="专家职称" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zjcz>
<field:cysj itemname="从业时间" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cysj>
<field:zjdt itemname="专家大图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zjdt>
<field:zysc itemname="专业擅长" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zysc>
<field:zjjj itemname="专家简介" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zjjj>
<field:zjxq itemname="专家详情" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zjxq>

<field:zztime itemname="坐诊时间" autofield="1" notsend="0" type="checkbox" isnull="true" islist="1" default="周一,周二,周三,周四,周五,周六,周日"  maxlength="250" page="">
</field:zztime>
