<li>
          <div class="img"> <img src="[field:zjdt function='GetOneImgUrl(@me,1)'/]"> </div>
          <div class="inform">
            <p class="zj_name">专家:[field:zjxm function='html2text(@me)'/]</p>
            <p class="zj_cv">简介:[field:zjjj function='cn_substr(Html2text("@me"),100)'/]</p>
            <p class="zj_des">擅长:[field:zysc function='cn_substr(Html2text("@me"),200)'/]</p>
            <a href="/swt/" class="phone">电话咨询</a> <a href="/swt/" class="yel">预约挂号</a> </li>
          </div>