<p>[field:description function="cn_substr(@me,200)"/]...<a href="[field:arcurl/]">[详细]</a></p>
		[field:typeurl/] 
         <ul>
		     <em></em>
           <li><a href="">医院简介</a></li>
           <li><a href="">先进设备</a></li>
           <li><a href="">医院环境</a></li>
           <li><a href="">医院荣誉</a></li>
           <li><a href="">来院路线</a></li>
           <li><a href="">预约挂号</a></li>
         </ul>
      </div>
      <div class="tabbox">
      <em><img src="{dede:global.cfg_cmsurl