<li >
                            <a href="[field:arcurl/]" target="_blank">
                                <div class="wz_doc1"><img src="[field:zjdt/]">
                                    <div class="wz_doctext"> <span> <b>[field:zjxm function='html2text(@me)'/]</b></span> <i>[field:zjcz/]</i>
                                        <div class="wz_doclink"> <b>专业擅长：</b>[field:cysj/]</div>
                                    </div>
                                </div>
                            </a>
                        </li>