<?php
$z[0]=Array("field","",47,69);
$z[0][4]['name']="typename";
$z[1]=Array("field","",100,121);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\n      <dd><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"></a>\n        <div class=\"child\">\n          <p><b>姓名：</b> [field:name/]</p>\n          <p><b>性别：</b> [field:sex/]</p>\n          <p><b>年龄：</b> [field:age/]岁</p>\n          <p><b>主治医生：</b> [field:doctor/]</p>\n          <p><b>病情描述：</b> [field:bqms/]</p>\n        </div>\n      </dd>\n      ",173,662);
$z[2][4]['row']="3";
$z[2][4]['addfields']="name,sex,age,doctor,bqms,story";
$z[2][4]['channelid']="18";
$z[2][4]['flag']="h";

?>