<?php
$z[0]=Array("global","",707,739);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",789,821);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("include","",862,897);
$z[2][4]['filename']="head.htm";
$z[3]=Array("global","",973,1005);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("channelartlist","\r\n                                            <div class=\"nav-info\" id=\"expert_11\">\r\n                                                <a href=\"{dede:field name='typeurl'/}\"><h3>{dede:field name='typename'/}</h3>\r\n                                                <span class=\"small-title\"><!--Hospital profile--></span></a>\r\n                                            </div>\r\n                                        ",1608,2085);
$z[4][4]['typeid']="2";
$z[4][4]['row']="4";
$z[5]=Array("global","",5584,5616);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",5991,6023);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",6184,6216);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",6359,6391);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",6705,6737);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("sql","  \r\n                                        [field:body/]  \r\n                                    ",7152,7327);
$z[10][4]['sql']="Select body from `dede_addonarticle` where aid=413";
$z[11]=Array("arclist"," \r\n                                        <img src=\"[field:picname/]\">\r\n                                    ",7596,7766);
$z[11][4]['row']="1";
$z[11][4]['typeid']="2";
$z[11][4]['idlist']="413";
$z[12]=Array("include","",10340,10375);
$z[12][4]['filename']="foot.htm";

?>