<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",91,120);
$z[1][4]['name']="position";
$z[2]=Array("field","",272,291);
$z[2][4]['name']="title";
$z[3]=Array("global","",459,484);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("field","",570,588);
$z[4][4]['name']="body";
$z[5]=Array("prenext","",1268,1293);
$z[5][4]['get']="pre";
$z[6]=Array("prenext","",1330,1356);
$z[6][4]['get']="next";
$z[7]=Array("arclist","\r\n        <li><a href=\"[field:arcurl/]\">[field:title/]</a><span><img src=\"/style/images/hotgif.gif\"></span></li>\r\n        ",1443,1633);
$z[7][4]['row']="4";
$z[7][4]['titlelen']="100";
$z[7][4]['orderby']="click";
$z[8]=Array("arclist","\r\n	<div class=\"zzys\">\r\n	  <b>[field:zjxm function='html2text(@me)'/]</b>\r\n	  <div class=\"zzys_pic\" style=\"margin-top:20px;\">\r\n	  <a href=\"/swt\"><img style=\"width: 275px;\" src=\"[field:zjdt function='GetOneImgUrl(@me,1)'/]\"></a></div>\r\n	</div>\r\n   ",2157,2527);
$z[8][4]['row']="1";
$z[8][4]['titlelen']="50";
$z[8][4]['typeid']="5";
$z[8][4]['addfields']="zjxm,zjcz,cysj,zjdt,zysc,zjjj,zjxq";
$z[8][4]['channelid']="19";
$z[9]=Array("include","",2618,2653);
$z[9][4]['filename']="foot.htm";

?>