<?php
$z[0]=Array("field","",77,105);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",111,140);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\n                     <dt>\n                        <img src=\"[field:picname/]\">\n                        <a href=\"[field:arcurl/]\">\n                           <b>[field:title/]</b>\n                           <p>[field:description function=\"cn_substr(@me,100)\"/]... <span>[详细]</span></p>\n                        </a>\n                     </dt>\n  ",209,632);
$z[2][4]['row']="1";
$z[2][4]['orderby']="click";
$z[2][4]['titlelen']="40";
$z[3]=Array("arclist","\n                       <a href=\"[field:arcurl/]\"><em></em>[field:title/]<span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></a>\n                      ",665,899);
$z[3][4]['row']="5";
$z[3][4]['orderby']="pubdate";
$z[3][4]['titlelen']="40";

?>