<li>
                <h1><img src="[field:litpic/]"></h1>
                <div class="team_ys right"> 
                  <div class="team_tit">
                     <b>张平<em></em></b>
                     <p>副主任医师<br>儿科经验30余年</p>
                   </div>
				   <div class="clear"></div>
                   <div class="team_ms">
                     <p>儿科经验30余年儿科经科经验30余年儿科经儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年</p>
                     <p><span>专业擅长：</span>儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年</p>
                     <p><span>专家简介：</span>30余年儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年儿科经验30余年<a href="[field:arcurl/]">【详细】</a></p>
                     
                     <div class="team_swt">
                     <a href="/swt/">我要和张主任直接对话</a></div>
                


                   </div>





                </div>
            </li>