<tr height="33">
                        <td class="bg_zjmz">付师亭</td>
                        <td>&nbsp;</td>
                        <td><a class="bg_zjmz4" href="javascript:void(0)" rel="nofollow" onclick="openZoosUrl('chatwin','&amp;e=预约付诗亭');return false;">预约</a></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
[field:zztime runphp=yes]
$arr=explode(",",@me);
@me = "";
for($index=0;$index<7;$index++){
@me=count($arr);
}
[/field:zztime]