<?php
$z[0]=Array("arclist","\r\n				 <h2>在这里，了解患者康复之路</h2>\r\n                  <h3 style=\"margin-left: 0px\">\r\n				  <img src=\"[field:zlqpic/]\"></h3>\r\n                  <h3><img src=\"[field:zlhpic/]\"></h3>\r\n                  <h4><img src=\"/style/images/kf.jpg\"></h4>\r\n                  <ul>\r\n                  <li style=\"margin-left: 0px\"><p><span class=\"s1\">治疗前</span>[field:zlqh/]</p></li>\r\n                  <li><p><span>治疗后</span>[field:zlh/]<a href=\"\">【详细】</a></p></li>\r\n                  </ul>\r\n				  ",191,811);
$z[0][4]['row']="1";
$z[0][4]['titlelen']="50";
$z[0][4]['addfields']="zlqh,zlh,zlqpic,zlhpic";
$z[0][4]['channelid']="18";

?>