<li>
          <div class="img"> <img src="[field:zjdt function='GetOneImgUrl(@me,1)'/]"> </div>
          <div class="inform">
            <p class="zj_name"><span>专家</span>[field:zjxm function='html2text(@me)'/]</p>
            <p class="zj_cv"><span>简介</span>[field:zjjj function='cn_substr(Html2text("@me"),35)'/]……</p>
            <p class="zj_des"><span>擅长</span>[field:zysc function='cn_substr(Html2text("@me"),80)'/]……</p>
            <div class="btn"><a href="/swt/" class="phone">电话咨询</a> <a href="/swt/" class="yel">预约挂号</a></div>
          </div>
         </li>