<?php
$z[0]=Array("global","",234,266);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1157,1189);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("type","[field:typeurl/]",3687,3738);
$z[2][4]['typeid']="11";
$z[3]=Array("global","",4544,4576);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",5129,5161);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",5224,5256);
$z[5][4]['name']="cfg_templets_skin";

?>