<?php
$z[0]=Array("global","",165,198);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("zlqpic","",252,298);
$z[1][4]['function']="GetOneImgUrl(@me,1)";
$z[2]=Array("global","",367,400);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("zlhpic","",453,499);
$z[3][4]['function']="GetOneImgUrl(@me,1)";
$z[4]=Array("global","",531,564);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("zlqh","",693,749);
$z[5][4]['function']="cn_substr(Html2text(\"@me\"),280)";
$z[6]=Array("zlh","",828,883);
$z[6][4]['function']="cn_substr(Html2text(\"@me\"),270)";
$z[7]=Array("arcurl","",892,907);

?>