<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",114,146);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",251,280);
$z[2][4]['name']="position";
$z[3]=Array("global","",344,376);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",468,500);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",3453,3488);
$z[5][4]['filename']="foot.htm";

?>