<?php
$z[0]=Array("arclist","\n        <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"/></a>\n        <div class=\"head\">[field:fulltitle/]</div>\n        <p class='info'>[field:infos/]……<a href=\"[field:arcurl/]\">[详细]</a></p>\n        ",45,323);
$z[0][4]['limit']="0,1";
$z[0][4]['flag']="p";
$z[0][4]['infolen']="255";
$z[1]=Array("arclist","\n            <p> <a href=\"[field:arcurl/]\">[field:fulltitle/]</a> <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> </p>\n            ",421,606);
$z[1][4]['limit']="1,3";
$z[2]=Array("arclist","\n            <p> <a href=\"[field:arcurl/]\">[field:fulltitle/]</a> <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span> </p>\n            ",673,858);
$z[2][4]['limit']="3,3";

?>