<li>
                                <img src="[field:picname/]">
                                <div class="child">
                                    <p><b>姓名：</b> [field:name/]</p>
                                    <p><b>性别：</b> [field:sex/]</p>
                                    <p><b>年龄：</b> [field:age/]岁</p>
                                    <p><b>主治医生：</b> [field:doctor/]</p>
                                    <p><b>病情描述：</b> [field:ms/]</p>
                                </div>
                            </li>