<?php
$z[0]=Array("field","",79,107);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",113,142);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                     <dt>\r\n                        <img src=\"[field:picname/]\">\r\n                        <a href=\"[field:arcurl/]\">\r\n                           <b>[field:title/]</b>\r\n                           <p>[field:description function=\"cn_substr(@me,100)\"/]... <span>[详细]</span></p>\r\n                        </a>\r\n                     </dt>\r\n  ",214,645);
$z[2][4]['row']="1";
$z[2][4]['orderby']="click";
$z[2][4]['titlelen']="40";
$z[3]=Array("arclist","\r\n                       <a href=\"[field:arcurl/]\"><em></em>[field:title/]<span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></a>\r\n                      ",680,916);
$z[3][4]['row']="5";
$z[3][4]['orderby']="pubdate";
$z[3][4]['titlelen']="40";

?>