<?php
$z[0]=Array("global","",157,190);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("zlqpic","",239,285);
$z[1][4]['function']="GetOneImgUrl(@me,1)";
$z[2]=Array("global","",350,383);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("zlhpic","",423,469);
$z[3][4]['function']="GetOneImgUrl(@me,1)";
$z[4]=Array("zlqh","",646,702);
$z[4][4]['function']="cn_substr(Html2text(\"@me\"),280)";
$z[5]=Array("zlh","",760,815);
$z[5][4]['function']="cn_substr(Html2text(\"@me\"),270)";
$z[6]=Array("arcurl","",824,839);

?>