<li>
                                <img src="{dede:global.cfg_cmsurl/}/style/image/1.png">
                                <div class="child">
                                    <p><b>姓名：</b> 小呆</p>
                                    <p><b>性别：</b> 男</p>
                                    <p><b>年龄：</b> 8岁</p>
                                    <p><b>主治医生：</b> 张师</p>
                                    <p><b>病情描述：</b> 特别好动，不能静坐，喜欢爬上爬下</p>
                                </div>
                            </li>