<?php
$z[0]=Array("field","",83,105);
$z[0][4]['name']="typename";
$z[1]=Array("field","",114,135);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\r\n						<p class=\"item-pic\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"/></a></p>\r\n						",159,307);
$z[2][4]['limit']="0,1";
$z[2][4]['flag']="p";
$z[3]=Array("arclist","\r\n							<p><a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n							",347,472);
$z[3][4]['limit']="0,2";
$z[3][4]['titlelen']="100";

?>