<?php
$z[0]=Array("global","",1469,1501);
$z[0][4]['name']="activepath";
$z[1]=Array("global","",1771,1826);
$z[1][4]['name']="backurl";
$z[1][4]['function']="urlencode(@me)";
$z[2]=Array("global","",2371,2403);
$z[2][4]['name']="activepath";
$z[3]=Array("global","",2617,2647);
$z[3][4]['name']="filename";
$z[4]=Array("global","",2770,2803);
$z[4][4]['name']="contentView";
$z[5]=Array("global","",3427,3458);
$z[5][4]['name']="extension";

?>