<?php
$z[0]=Array("global","",135,161);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",209,239);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",280,307);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",367,392);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",433,458);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",517,542);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n                                    <a href=\"[field:typelink/]\"  title=\"[field:typename/]\">[field:typename/]</a>\r\n								   ",1658,1860);
$z[6][4]['type']="son";
$z[6][4]['typeid']="12";
$z[7]=Array("channel","\r\n                                    <a href=\"[field:typelink/]\"  title=\"[field:typename/]\">[field:typename/]</a>\r\n								   ",2163,2365);
$z[7][4]['type']="son";
$z[7][4]['typeid']="13";
$z[8]=Array("channel","\r\n                                    <a href=\"[field:typelink/]\"  title=\"[field:typename/]\">[field:typename/]</a>\r\n								   ",2647,2849);
$z[8][4]['type']="son";
$z[8][4]['typeid']="14";
$z[9]=Array("channel","\r\n                                    <a href=\"[field:typelink/]\"  title=\"[field:typename/]\">[field:typename/]</a>\r\n								   ",3143,3345);
$z[9][4]['type']="son";
$z[9][4]['typeid']="50";
$z[10]=Array("global","",4824,4849);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("global","",6302,6327);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("arclist","\r\n            <li><a href=\"[field:banurl/]\"><img src=\"[field:picname/]\" alt=\"\"></a></li>\r\n        ",6689,6890);
$z[12][4]['row']="3";
$z[12][4]['typeid']="72";
$z[12][4]['addfields']="banurl";
$z[12][4]['channelid']="17";
$z[13]=Array("global","",7066,7091);
$z[13][4]['name']="cfg_cmsurl";

?>