<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("list","\n		   <li>	   \n                    <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:picname/]\" alt=\"\">\n                        <i><img src=\"{dede:global.cfg_templets_skin/}/images/shipinbf.png\" alt=\"播放\"></i></a>\n                    <a href=\"[field:arcurl/]\" target=\"_blank\">[field:description function=\"cn_substr(@me,90)\"/]...<span>[详细]</span></a>\n             </li>\n			",175,601);
$z[1][4]['pagesize']="12";
$z[2]=Array("include","",648,683);
$z[2][4]['filename']="foot.htm";

?>