<?php
$z[0]=Array("field","",114,136);
$z[0][4]['name']="typename";
$z[1]=Array("field","",176,198);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",237,262);
$z[2][4]['name']="description";
$z[3]=Array("global","",312,344);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",405,437);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",472,504);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",554,589);
$z[6][4]['filename']="head.htm";
$z[7]=Array("channelartlist","\n    <dl>\n      <dt class=\"typetit\">\n        <h2>\n          <b>{dede:field.typename/}患儿故事</b><span><a href=\"{dede:field.typeurl/}\">更多故事&gt;&gt;</a></span>\n        </h2>\n      </dt>\n      {dede:arclist row=\"3\" addfields='name,sex,age,doctor,bqms,story' channelid='18'}\n      <dd><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"></a>\n        <div class=\"child\">\n          <p><b>姓名：</b> [field:name/]</p>\n          <p><b>性别：</b> [field:sex/]</p>\n          <p><b>年龄：</b> [field:age/]岁</p>\n          <p><b>主治医生：</b> [field:doctor/]</p>\n        </div>\n        <div class=\"des\"><b>病情描述：</b>[field:bqms/]<a href=\"[field:arcurl/]\">[详情]</a></div>\n      </dd>\n      {/dede:arclist}\n    </dl>\n    ",642,1456);
$z[7][4]['typeid']="6";
$z[7][4]['type']="son";
$z[8]=Array("type"," <a href=\"[field:typelink/]\" target=\"_blank\"></a><!--来院路线--> \n    ",1778,1888);
$z[8][4]['typeid']="11";
$z[9]=Array("type"," <a href=\"[field:typelink/]\" target=\"_blank\" title=\"[field:typename/]\"></a><!--医师团队--> \n    ",2027,2162);
$z[9][4]['typeid']="5";
$z[10]=Array("include","",2177,2212);
$z[10][4]['filename']="foot.htm";

?>