<?php
$z[0]=Array("field","",114,136);
$z[0][4]['name']="typename";
$z[1]=Array("field","",176,198);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",237,262);
$z[2][4]['name']="description";
$z[3]=Array("global","",312,344);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",405,437);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",472,504);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",554,589);
$z[6][4]['filename']="head.htm";
$z[7]=Array("field","",700,722);
$z[7][4]['name']="typename";
$z[8]=Array("field","",753,774);
$z[8][4]['name']="typeurl";
$z[9]=Array("arclist","\n      <dd><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\"></a>\n        <div class=\"child\">\n          <p><b>姓名：</b> [field:name/]</p>\n          <p><b>性别：</b> [field:sex/]</p>\n          <p><b>年龄：</b> [field:age/]岁</p>\n          <p><b>主治医生：</b> [field:doctor/]</p>\n        </div>\n        <div class=\"des\"><b>病情描述：</b>[field:bqms/]<a href=\"[field:arcurl/]\">[详情]</a></div>\n      </dd>\n      ",840,1372);
$z[9][4]['row']="12";
$z[9][4]['addfields']="name,sex,age,doctor,bqms,story";
$z[9][4]['channelid']="18";
$z[10]=Array("type"," <a href=\"[field:typelink/]\" target=\"_blank\"></a><!--来院路线--> \n    ",1704,1814);
$z[10][4]['typeid']="11";
$z[11]=Array("type"," <a href=\"[field:typelink/]\" target=\"_blank\" title=\"[field:typename/]\"></a><!--医师团队--> \n    ",1953,2088);
$z[11][4]['typeid']="5";
$z[12]=Array("include","",2103,2138);
$z[12][4]['filename']="foot.htm";

?>