<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("list","\r\n		   <li>	   \r\n                    <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:picname/]\" alt=\"\">\r\n                        <i><img src=\"/style/images/shipinbf.png\" alt=\"播放\"></i></a>\r\n                    <a href=\"[field:arcurl/]\" target=\"_blank\">[field:description function=\"cn_substr(@me,90)\"/]...<span>[详细]</span></a>\r\n             </li>\r\n			",181,587);
$z[1][4]['pagesize']="12";
$z[2]=Array("include","",649,684);
$z[2][4]['filename']="foot.htm";

?>