<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",89,118);
$z[1][4]['name']="position";
$z[2]=Array("field","",264,283);
$z[2][4]['name']="title";
$z[3]=Array("global","",314,340);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",371,402);
$z[4][4]['name']="cfg_hospital_tel";
$z[5]=Array("global","",470,502);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("field","",596,617);
$z[6][4]['name']="content";
$z[7]=Array("prenext","",1696,1721);
$z[7][4]['get']="pre";
$z[8]=Array("prenext","",1757,1783);
$z[8][4]['get']="next";
$z[9]=Array("arclist","\n        <li><a href=\"[field:arcurl/]\">[field:title/]</a><span><img src=\"{dede:global.cfg_templets_skin/}/images/hotgif.gif\"></span></li>\n        ",1865,2079);
$z[9][4]['row']="4";
$z[9][4]['titlelen']="100";
$z[9][4]['orderby']="click";
$z[10]=Array("arclist","\n	<div class=\"zzys\">\n	  <b>[field:zjxm function='html2text(@me)'/]</b>\n	  <div class=\"zzys_pic\" style=\"margin-top:20px;\">\n	  <a href=\"/swt\"><img style=\"width: 275px;\" src=\"[field:zjdt function='GetOneImgUrl(@me,1)'/]\"></a></div>\n	</div>\n   ",2585,2949);
$z[10][4]['row']="1";
$z[10][4]['titlelen']="50";
$z[10][4]['typeid']="5";
$z[10][4]['addfields']="zjxm,zjcz,cysj,zjdt,zysc,zjjj,zjxq";
$z[10][4]['channelid']="19";
$z[11]=Array("include","",3030,3065);
$z[11][4]['filename']="foot.htm";

?>