<?php
$z[0]=Array("global","",85,117);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",210,242);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",340,372);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",465,497);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",590,622);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("type","[field:typeurl/]",684,735);
$z[5][4]['typeid']="11";
$z[6]=Array("global","",747,779);
$z[6][4]['name']="cfg_templets_skin";

?>