<?php
$z[0]=Array("channelartlist","\n						<div class=\"nav-info\" id=\"expert_{dede:field.id/}\">\n							<a href=\"{dede:field.typeurl/}\"><h3>{dede:field.typename/}</h3>\n							<span class=\"small-title\"></span></a>\n		    			</div>\n					",288,560);
$z[0][4]['typeid']="2,3,5,78,139,8,89,11,10";
$z[1]=Array("global","",711,743);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",917,949);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1118,1150);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("type","[field:typeurl/]",1278,1329);
$z[4][4]['typeid']="11";
$z[5]=Array("global","",1351,1383);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1520,1552);
$z[6][4]['name']="cfg_templets_skin";

?>