<?php
$z[0]=Array("global","",83,109);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",149,181);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",230,262);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",319,351);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",423,455);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",515,559);
$z[5][4]['filename']="common/header.htm";
$z[6]=Array("include","",590,641);
$z[6][4]['filename']="common/public_banner.htm";
$z[7]=Array("list","\n    		<div class=\"item\">\n				<img src=\"[field:litpic/]\">\n				<div class=\"info\">\n					<strong><a href=\"[field:arcurl/]\">[field:title/]</a></strong>\n					<p>[field:description/]……<a href=\"[field:arcurl/]\">[详细]</a></p>\n				</div>\n			</div>\n			",794,1081);
$z[7][4]['titlelen']="100";
$z[8]=Array("pagelist","",1142,1208);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="1";
$z[9]=Array("include","",1228,1276);
$z[9][4]['filename']="common/list_right.htm";
$z[10]=Array("include","",1286,1330);
$z[10][4]['filename']="common/footer.htm";

?>