document.writeln("<link rel=\'stylesheet\' href=\'http://www.cdkid.cn/style/css/plugins_animate.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'http://at.alicdn.com/t/font_7cyf6p887kz9f6r.css\'>");
document.writeln("<style>");
document.writeln("html, body, h1, h2, h3, h4, h5, h6, div, dl, dt, dd, ul, ol, li, p, blockquote, pre, hr, figure, table, caption, th, td, form, fieldset, legend, input, button, textarea, menu { margin: 0;  }");
document.writeln("");
document.writeln("header, footer, section, article, aside, nav, hgroup, address, figure, figcaption, menu, details { display: block; }");
document.writeln("");
document.writeln("table { border-collapse: collapse; border-spacing: 0; }");
document.writeln("");
document.writeln("caption, th { text-align: left; font-weight: normal; }");
document.writeln("");
document.writeln("html, body, fieldset, img, iframe, abbr { border: 0; }");
document.writeln("");
document.writeln("i, cite, em, var, address, dfn { font-style: normal; }");
document.writeln("");
document.writeln("[hidefocus], summary { outline: 0; }");
document.writeln("");
document.writeln("li { list-style: none; }");
document.writeln("");
document.writeln("");
document.writeln("sup, sub { font-size: 83%; }");
document.writeln("");
document.writeln("pre, code, kbd, samp { font-family: inherit; }");
document.writeln("");
document.writeln("q:before, q:after { content: none; }");
document.writeln("");
document.writeln("textarea { overflow: auto; resize: none; }");
document.writeln("");
document.writeln("label, summary { cursor: default; }");
document.writeln("");
document.writeln("a, button { cursor: pointer; }");
document.writeln("");
document.writeln("h1, h2, h3, h4, h5, h6, em, b, p, span { font-weight: lighter; }");
document.writeln("");
document.writeln("del, ins, u, s, a, a:hover { text-decoration: none; }");
document.writeln("");
document.writeln("body, textarea, input, button, select, keygen, legend { font: 12px/1.14 \'Microsoft YaHei\', \/\/5b8b\/\/4f53; color: #4b4b4b; outline: 0; }");
document.writeln("");
document.writeln("body { background: #fff; }");
document.writeln("");
document.writeln("a, a:hover { color: #4b4b4b; }");
document.writeln(".site-fixed { position: fixed; top: 125px; right: 0; z-index: 10; }");
document.writeln(".site-fixed .fixed-item { position: absolute; margin-bottom: 20px; font-size: 0; right: -214px; }");
document.writeln(".site-fixed .fixed-item.apply-fixed { top: 115px; }");
document.writeln(".site-fixed .fixed-item.contact-fixed:hover { transition: right ease .9s; right: 0; }");
document.writeln(".site-fixed .fixed-item.contact-fixed:hover + .apply-fixed { top: 285px; }");
document.writeln(".site-fixed .fixed-item.apply-fixed:hover { transition: right ease .9s; right: 0; top: 145px; }");
document.writeln(".site-fixed .fixed-item .item-before { position: absolute; left: -30px; top: 30px; display: inline-block; padding: 10px 5px; background: #fff; border-radius: 6px 0 0 6px; text-align: center; cursor: pointer; vertical-align: middle; box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1); }");
document.writeln(".site-fixed .fixed-item .item-before .iconfont { color: #cc244c; font-size: 20px; display: block; }");
document.writeln(".site-fixed .fixed-item .item-before .text-shu { display: inline-block; width: 14px; margin: 0 auto; font-size: 14px; color: #616161; line-height: 14px; }");
document.writeln(".site-fixed .fixed-item .item-content { display: inline-block; background: #fff; border-radius: 6px 0 0 6px; padding: 12px 18px; vertical-align: middle; box-shadow: 6px 0 10px 2px rgba(0, 0, 0, 0.1); width: 178px; }");
document.writeln(".site-fixed .fixed-item .item-content .fixec-code { padding: 15px 0; text-align: center; font-size: 12px; color: #000; border-bottom: 1px solid #f6f6f6; }");
document.writeln(".site-fixed .fixed-item .item-content .fixec-code .item-msg { font-size: 16px; margin-top: 6px; }");
document.writeln(".site-fixed .fixed-item .item-content .fixed-btn { display: block; width: 103px; height: 27px; line-height: 27px; font-size: 14px; color: #fff; text-align: center; background: #cc244c; border-radius: 4px; margin: 10px auto 0; }");
document.writeln(".site-fixed .fixed-item .item-content .list-item { padding: 12px 0; border-bottom: 1px solid #f6f6f6; transition: all linear .9s; }");
document.writeln(".site-fixed .fixed-item .item-content .list-item:hover { color: #cc244c; }");
document.writeln(".site-fixed .fixed-item .item-content .list-item:hover .title { color: #cc244c; }");
document.writeln(".site-fixed .fixed-item .item-content .list-item:hover .text { color: #cc244c; }");
document.writeln(".site-fixed .fixed-item .item-content .list-item:last-child { border: none; }");
document.writeln(".site-fixed .fixed-item .item-content .list-item .iconfont { display: inline-block; height: 20px; line-height: 20px; font-size: 19px; vertical-align: top; margin-right: 10px; }");
document.writeln(".site-fixed .fixed-item .item-content .list-item .title { display: inline-block; line-height: 20px; height: 20px; font-size: 16px; color: #000; margin-bottom: 4px; transition: all linear .9s; }");
document.writeln(".site-fixed .fixed-item .item-content .list-item .text { font-size: 16px; color: #444444; padding-left: 26px; transition: all linear .9s; }");
document.writeln(".site-fixed .fixed-item .item-content .list-item .text .small-text { font-size: 12px; }");
document.writeln("	</style>");
document.writeln("	<div class=\'site-fixed\'> ");
document.writeln("		<div class=\'fixed-item contact-fixed animated\'> ");
document.writeln("			<div class=\'item-before\'> ");
document.writeln("				<span class=\'iconfont icon-dianhua\'></span> ");
document.writeln("				<div class=\'text-shu\'>联系方式</div> ");
document.writeln("			</div> ");
document.writeln("			<div class=\'item-content\'> ");
document.writeln("				<ul class=\'content-list\'> ");
document.writeln("					<li class=\'list-item\'> <span class=\'iconfont icon-dianhua\'></span> <span class=\'title\'>联系电话</span> <p class=\'text\'>028-62520775</p> </li>  ");
document.writeln("					<li class=\'list-item\'> <a href=\'http://wpa.qq.com/msgrd?v=3&amp;uin=1205911621&amp;site=qq&amp;menu=yes\' target=\'_blank\'> <span class=\'iconfont icon-qq\'></span> <span class=\'title\'>客服QQ</span> <p class=\'text\'>1205911621</p> </a> </li> ");
document.writeln("					<li class=\'list-item\'> <span class=\'iconfont icon-youxiang\'></span> <span class=\'title\'>联系邮箱</span> <p class=\'text\'><span class=\'small-text\'>cdtsetyy@163.com</span></p> </li> ");
document.writeln("				</ul> ");
document.writeln("			</div> ");
document.writeln("		</div> ");
document.writeln("		<div class=\'fixed-item apply-fixed animated\'> ");
document.writeln("			<div class=\'item-before\'> ");
document.writeln("				<span class=\'iconfont icon-zaixianyuyue\'></span> ");
document.writeln("				<div class=\'text-shu\'>在线预约</div> ");
document.writeln("			</div> ");
document.writeln("			<div class=\'item-content\'> ");
document.writeln("				<div class=\'fixec-code\'> ");
document.writeln("					<img src=\'/images/tianshi_app.jpg\' width=\'122\' height=\'122\' /> ");
document.writeln("					<p class=\'text\'>扫码关注成都天使儿童医院官方APP</p> ");
document.writeln("					<h2 class=\'item-msg\'>咨询 / 预约 / 随访</h2> ");
document.writeln("				</div> ");
document.writeln("				<a href=\'http://put.zoosnet.net/LR/Chatpre.aspx?id=PUT12012741&lng=cn\' class=\'fixed-btn\'>快速预约</a> ");
document.writeln("			</div> ");
document.writeln("		</div> ");
document.writeln("	</div> ");



document.writeln('<script language="javascript" src="http://put.zoosnet.net/JS/LsJS.aspx?siteid=PUT12012741&float=0&lng=cn"></script>');
document.write('<style>#LRdiv2{display:none !important;}</style>');
document.writeln('<script type="text/javascript" src="/swt/center.js"></script>');
document.writeln('<script type="text/javascript" src="/style/js/angel_order.js"></script>');